### ISSUE TITLE
no way to generate acceptable password

### ISSUE THREAD

**Issue by ivan-sirosh** [authelia/authelia#1002]
Hi,
I have tried to generate a password by following documentation
`docker run authelia/authelia:latest authelia hash-password test`
and also by
`https://argon2.online/`

but did not have any luck to proceed with correct user credentials

example of configuration:
```yaml
access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: secure.example.com
      policy: one_factor
      subject:
        - "group:admins"
        - "group:moderators"
    - domain: public.example.com
      policy: bypass
```

```yaml
users:
  authelia:
    password: "$argon2id$v=19$m=16,t=2,p=1$R1pWdVVQbnJxeFZEWVducw$yELXF/6dYFcs3KNygPTN1A" # Password is 'test'
    email: test@example.com
    groups:
      - admins
      - dev
```

after trying to access service by login/password few times, the authelia service goes down and traefik shows error 
`middleware "authelia@docker" does not exist `

software versions:
* authelia/authelia:4.18
* traefik:v2.2.0

errors from authelia
```
time="2020-05-10T13:10:53Z" level=error msg="Credentials are wrong for user test@example.com" method=POST path=/api/firstfactor remote_ip=227.101.103.38 stack="github.com/authelia/authelia/internal/middlewares/authelia_context.go:64 (*AutheliaCtx).Error\ngithub.com/authelia/authelia/internal/handlers/response.go:94            handleAuthenticationUnauthorized\ngithub.com/authelia/authelia/internal/handlers/handler_firstfactor.go:52 FirstFactorPost\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:49 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.0.4/router.go:443                          (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14      LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.12.0/server.go:2087                       (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.12.0/workerpool.go:223                    (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.12.0/workerpool.go:195                    (*workerPool).getCh.func1\nruntime/asm_amd64.s:1373                                                      goexit"
```

**Comment by james-d-elliott** [comment]
Can you try authelia/authelia:fix-salt-encoding - we had a bug in the upstream library we used that caused some headache and this should fix it locally while we wait for an upstream fix.

**Comment by ivan-sirosh** [comment]
still the same almost

I have performed next commands

```
docker run authelia/authelia:fix-salt-encoding authelia hash-password -h              
Hash a password to be used in file-based users database. Default algorithm is argon2id.

Usage:
  authelia hash-password [password] [flags]

Flags:
  -h, --help              help for hash-password
  -i, --iterations int    set the number of hashing iterations (default 1)
  -k, --key-length int    [argon2id] set the key length param (default 32)
  -m, --memory int        [argon2id] set the amount of memory param (in MB) (default 1024)
  -p, --parallelism int   [argon2id] set the parallelism param (default 8)
  -s, --salt string       set the salt string
  -l, --salt-length int   set the auto-generated salt length (default 16)
  -z, --sha512            use sha512 as the algorithm (changes iterations to 50000, change with -i)
```
and
```
docker run authelia/authelia:fix-salt-encoding authelia hash-password -m 128 -i 2 test
```

then I added test user
```
users:
  test:
    password: "$argon2id$v=19$m=131072,t=2,p=8$M1FkMDZTZ0EwWlljYlJ3eQ$fCl4tAmB6meowZOoHlb8lBbkXhYxAqsezxWIALT2tgE" # Password is 'test'
    email: test@example.com
    groups:
      - admins
      - dev
```
then change configuration according to the commands above
```
authentication_backend:
  disable_reset_password: true
  file:
    path: /etc/authelia/users_database.yml
    password:
      algorithm: argon2id
      key_length: 32
      iterations: 2
      salt_length: 16
      parallelism: 8
      memory: 128
```

each try of entering login/password - restarts a container

```
docker service ps bln_authelia
ID                  NAME                 IMAGE                                 NODE                DESIRED STATE       CURRENT STATE                ERROR                         PORTS
pc1emclpwxzp        bln_authelia.1       authelia/authelia:fix-salt-encoding   edge                Running             Running about a minute ago                                 
ingjc779qelc         \_ bln_authelia.1   authelia/authelia:fix-salt-encoding   edge                Shutdown            Failed about a minute ago    "task: non-zero exit (137)"   
gg18ve60kvzq         \_ bln_authelia.1   authelia/authelia:fix-salt-encoding   edge                Shutdown            Failed 2 minutes ago         "task: non-zero exit (137)"   
ly4h9xmgvle5         \_ bln_authelia.1   authelia/authelia:fix-salt-encoding   edge                Shutdown            Failed 4 minutes ago         "task: non-zero exit (137)"   
kazr51c0qwec         \_ bln_authelia.1   authelia/authelia:fix-salt-encoding   edge                Shutdown            Failed 5 minutes ago         "task: non-zero exit (137)" 
```

also nothing special in logs
```
cat /authelia/log 
time="2020-05-11T13:07:42Z" level=info msg="Logging severity set to debug"
time="2020-05-11T13:07:42Z" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:9091"
```

**Comment by james-d-elliott** [comment]
Are you running into some kind of memory limit maybe? Argon2id consumes RAM temporarily while hashing.

**Comment by ivan-sirosh** [comment]
You were right, problem has gone after increasing memory size.

can summarize that next solutions are helpful:
* image authelia/authelia:fix-salt-encoding
* increasing memory size for container

**Comment by ivan-sirosh** [comment]
also I tested sha512 - it works as expected

**Comment by james-d-elliott** [comment]
@ivan-sirosh great to hear it's resolved. Some information about the memory used, it only technically uses the memory for the hashing period. It will *look* like it's longer but it's just not freed by the OS yet, and given memory pressure it will automatically reclaim that allocation.

**Comment by nightah** [comment]
> * increasing memory size for container

Docker by default doesn't set a maximum memory size on container unless there's something I've missed of recent times?

**Comment by ivan-sirosh** [comment]
@nightah I use docker in swarm mode with resource limitation for containers.
https://docs.docker.com/compose/compose-file/#resources

**Comment by poldim** [comment]
Just a heads up in case anyone else ends up here with a similar incorrect user/password combo.  I spent more time troubleshooting this than I'd want to admit.

The login username should be the one defined directly under `users` and not the display name.  **They are case-sensitive**, so `Bob` will result in no user match and thus no login while `bob` will work.

```yaml
users:
  bob:
    displayname: "Bob"
```

**Comment by daerlnaxe** [comment]
Ho god, big thx !
