### ISSUE TITLE
Can't paste TOTP token on osx firefox

### ISSUE THREAD

**Issue by Xyv** [authelia/authelia#1763]
Hey,

I am not able to paste the TOTP token on firefox 86.0 running on osx 10.14, even with all extensions disabled.
Trying to paste the token would only fill the first digit and move the focus to the next div.
I suspect this is due to the `maxlength` attribute on the div and something is blocking the autofill of the next divs.

I've tried to change the  `editor.truncate_user_pastes` from `true` to `false` in `about:config` but this completely disable pasting the token, not even the first digit is filled in this case.

I've seen https://github.com/authelia/authelia/issues/956 and https://github.com/authelia/authelia/issues/1206 but there was no mention of firefox. It works perfectly fine on safari and chrome.

Thanks for all your work!

**Comment by james-d-elliott** [comment]
Which version of Authelia?

**Comment by james-d-elliott** [comment]
I'm assuming this is fixed, if it's not feel free to open it again.

**Comment by Xyv** [comment]
Oh, I must have missed the notification from your previous comment. The issue is still present for me.
I am on the latest docker version running on arm: `Authelia version v4.27.1, build 2fabfecb55114b7242865fce33059792db3f6518`

**Comment by james-d-elliott** [comment]
None of us use OSX so it may take us a while to reproduce it. I do note that the second time I try to paste it fails, but the first time it works fine. Is this your experience or do you see it all the time?

**Comment by Xyv** [comment]
It fails everytime for me.More precisely, it pastes the first digit then moves the focus to the next div. If I try pasting again it fills the same digit and goes to the next div, etc. So if totp is `123456`, the best I can have after multiple pastes command is `111111`.

When you say it fails the second time what happens? Nothing is pasted or just the first digit ?

If I can help debug this let me know.

**Comment by james-d-elliott** [comment]
Same thing as you're describing. But the first one always works flawlessly. Are you using a password manager that copies the code?

**Comment by Xyv** [comment]
Yes, Bitwarden. But I've also tried with all extension deactivated and manually copy/pasting.

**Comment by nightah** [comment]
@Xyv is this still an issue for you?
If so can you include your version of OSX and Firefox?

**Comment by Xyv** [comment]
Hey @nightah, thanks for checking in.
This is still an issue for me yes, on latest firefox (94.0.1) and latest macOS Mojave (10.14.6) (So an old osx version!)
Can't say if this is still the case on latest osx version, for various reasons I can't upgrade past Mojave for now.

I've tried on linux and the issue is not present.

**Comment by nightah** [comment]
So I've just tried to reproduce this unsuccessfully with the following software versions.

OSX: 10.13.6 High Sierra
Firefox: 95.0b9

Unfortunately, I have an old Mac but I think whatever is causing the issue is likely to be a configuration option in Firefox given your experience with the other browsers. Having said that Firefox with default settings does not appear to be an issue for me.

**Comment by Xyv** [comment]
Fair enough.

I've done some more searching on the mac and it appears the culprit is the `dom.event.clipboardevents.enabled = False`. Which if I recall correctly I mostly used to allow pasting content on website that prevents it. 

I'll try to set this on a windows/linux machine in the following days to see if I can reproduce there too.

Still feeling this settings should not cause trouble to paste the TOTP but I can understand you have other priorities.
Thanks for spending time on it, and thanks again for this amazing  tool 👍

**Comment by BapRx** [comment]
Hello, I have the same issue in a different configuration :
```
Device: Google Pixel 6 Pro
OS: Android 12
Browser: Brave (same result with Google Chrome)
```
The first digit is filled leaving the others empty.

**Comment by nightah** [comment]
@Xyv if that's the case maybe try something that only disables clipboard events conditionally for the websites you want like [this extension](https://addons.mozilla.org/en-US/firefox/addon/don-t-fuck-with-paste/).

I try to put some time aside to understand why this is occurring when disabled, but I suspect it's something to do with how the react-otp plugin handles pastes and it likely relies on the eventhandler.
